### ISSUE TITLE
Image Library

### ISSUE THREAD

**Issue by sjk06** [oslabs-beta/NextView#61]
![NextView-banner-final-900x300](https://github.com/oslabs-beta/NextView/assets/101832001/fd3242b4-3af5-42ea-96ff-81b288ef8c66)

**Comment by sjk06** [comment]
![dashboard-overview](https://github.com/oslabs-beta/NextView/assets/101832001/9f22cba0-3a6d-476d-8649-b9661c9688c4)

**Comment by sjk06** [comment]
![Screenshot 2023-06-21 at 1 25 46 PM](https://github.com/oslabs-beta/NextView/assets/101832001/4bbb2dab-96ec-459d-a728-816241ec9763)

**Comment by Scott-Brasko** [comment]
![NextView-banner-final-final](https://github.com/oslabs-beta/NextView/assets/120596825/87836435-91c4-4081-9bdd-60e14af9dee5)
